In [5]:
#Loading and Preprocessing

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.datasets import fetch_california_housing
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

housing = fetch_california_housing()
df = pd.DataFrame(housing.data, columns=housing.feature_names)

df['MedHouseVal'] = housing.target
df.head()

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude,MedHouseVal
0,8.3252,41.0,6.984127,1.023810,322.0,2.555556,37.88,-122.23,4.526
1,8.3014,21.0,6.238137,0.971880,2401.0,2.109842,37.86,-122.22,3.585
2,7.2574,52.0,8.288136,1.073446,496.0,2.802260,37.85,-122.24,3.521
3,5.6431,52.0,5.817352,1.073059,558.0,2.547945,37.85,-122.25,3.413
4,3.8462,52.0,6.281853,1.081081,565.0,2.181467,37.85,-122.25,3.422

In [6]:
df.isnull().sum()

MedInc         0
HouseAge       0
AveRooms       0
AveBedrms      0
Population     0
AveOccup       0
Latitude       0
Longitude      0
MedHouseVal    0
dtype: int64

In [7]:
#Feature Scaling

X = df.drop('MedHouseVal', axis=1)
y = df['MedHouseVal']

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)


X_scaled = pd.DataFrame(X_scaled, columns=X.columns)

X_scaled.head()

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude
0,2.344766,0.982143,0.628559,-0.153758,-0.974429,-0.049597,1.052548,-1.327835
1,2.332238,-0.607019,0.327041,-0.263336,0.861439,-0.092512,1.043185,-1.322844
2,1.782699,1.856182,1.155620,-0.049016,-0.820777,-0.025843,1.038503,-1.332827
3,0.932968,1.856182,0.156966,-0.049833,-0.766028,-0.050329,1.038503,-1.337818
4,-0.012881,1.856182,0.344711,-0.032906,-0.759847,-0.085616,1.038503,-1.337818

The California Housing dataset was first loaded using sklearn and converted into a pandas DataFrame for easier handling and analysis.
The target variable (median house value) was added to the dataset as a separate column to clearly distinguish between input features and the output variable.
The dataset was checked for missing values using isnull(), and no missing values were found, so no cleaning was required.
Feature scaling was then applied using StandardScaler to normalize the input features. This ensures that all features are on the same scale, which helps improve the performance and accuracy of machine learning models, especially those sensitive to feature magnitude.

In [8]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X_scaled, y, test_size=0.2, random_state=42
)

In [10]:
#Linear Regression

from sklearn.linear_model import LinearRegression
lr = LinearRegression()
lr.fit(X_train, y_train)
y_pred_lr = lr.predict(X_test)

Linear Regression finds a linear relationship between input features and output.
It is simple and works well for basic patterns.

In [11]:
#Decision Tree Regressor

from sklearn.tree import DecisionTreeRegressor
dt = DecisionTreeRegressor(random_state=42)
dt.fit(X_train, y_train)
y_pred_dt = dt.predict(X_test)

Decision Tree splits the data into branches based on conditions.
It can capture complex relationships but may overfit.

In [12]:
#Model Evaluation and Comparison

from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
def evaluate(y_test, y_pred):
    mse = mean_squared_error(y_test, y_pred)
    mae = mean_absolute_error(y_test, y_pred)
    r2 = r2_score(y_test, y_pred)
    return mse, mae, r2

# Evaluate models
lr_metrics = evaluate(y_test, y_pred_lr)
dt_metrics = evaluate(y_test, y_pred_dt)

print("Linear Regression:", lr_metrics)
print("Decision Tree:", dt_metrics)

Linear Regression: (0.5558915986952441, 0.5332001304956565, 0.575787706032451)
Decision Tree: (0.4942716777366763, 0.4537843265503876, 0.6228111330554302)

In [13]:
results = pd.DataFrame({
    "Model": ["Linear Regression", "Decision Tree"],
    "MSE": [lr_metrics[0], dt_metrics[0]],
    "MAE": [lr_metrics[1], dt_metrics[1]],
    "R2 Score": [lr_metrics[2], dt_metrics[2]]
})

results

               Model       MSE       MAE  R2 Score
0  Linear Regression  0.555892  0.533200  0.575788
1      Decision Tree  0.494272  0.453784  0.622811

The performance of Linear Regression and Decision Tree was compared using MSE, MAE, and R² score.

Decision Tree has lower MSE and MAE values compared to Linear Regression, which means it has less prediction error.

It also has a higher R² score, indicating that it explains the data better.

Therefore, Decision Tree performs better than Linear Regression for this dataset.